language: java
jdk:
  - openjdk11
install: true
script:
  - chmod +x gradlew
  - ./gradlew clean build

deploy:
  provider: heroku
  api_key: 075d245b-a11c-4542-950d-26764c1d2781
  app: kpchat
  on: dev

branches:
  only:
    - dev

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
