language: java
jdk:
  - openjdk11
install: true
script:
  - chmod +x gradlew
  - ./gradlew clean build

branches:
  only:
    - dev

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
